---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-pod
  labels:
    app: hello-world-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: jozefzatko/docker-hello-example:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 200Mi
            cpu: 200m
          limits:
            memory: 500Mi
            cpu: 500m