---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod-2
  labels:
    app: hello-world
spec:
  restartPolicy: Never
  containers:
  - name: hello-world
    image: jozefzatko/docker-hello-example:1.0.0
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: 200Mi
        cpu: 200m
      limits:
        memory: 500Mi
        cpu: 500m
